### ISSUE TITLE
The output does only open on first Safari Window

### ISSUE THREAD

**Issue by designerfuzzi** [marekpiechut/translate#5]
translating works, but the popup does open allways on a different window then the one you choosed from which text you like translated. Ends up in a popup theater, its somewhere but not where you look at.
A actuall visible window check is needed here before fire/showing popup.

**Comment by marekpiechut** [comment]
Fixed in release v1.0.5 Please update.

**Comment by designerfuzzi** [comment]
tested again!
works perfect!
thank you very much.
